=== sangitamane/headless-cms/src/views/partials/elements-components-templates/eds-c-footer/data/eds-c-footer.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://springernature.com/eds-c-footer.schema.json",
    "title": "Footer",
    "description": "Footer component",
    "type": "object",
    "properties": {
      "dataTest": { "type": "string" },
      "dataTrackComponent": { "type": "string" },
      "navigation": {
        "type": "object",
        "properties": {
          "links": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": { "type": "string" },
                "buttonProperties": { "type": "string" },
                "url": { "type": "string" },
                "dataAttributes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "enum": [
                          "test",
                          "track",
                          "track-context",
                          "track-value",
                          "track-method",
                          "track-content-type",
                          "track-item-id",
                          "track-type",
                          "track-action",
                          "track-category",
                          "track-label",
                          "track-component"
                        ]
                      },
                      "value": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "value"
                    ]
                  }
                }
              },
              "required": ["text"]
            }
          }
        },
        "required": ["links"]
      },
      "productGroups": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "url": { "type": "string" },
                  "text": { "type": "string" },
                  "dataAttributes": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "enum": [
                            "test",
                            "track",
                            "track-context",
                            "track-value",
                            "track-method",
                            "track-content-type",
                            "track-item-id",
                            "track-type",
                            "track-action",
                            "track-category",
                            "track-label",
                            "track-component"
                          ]
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "value"
                      ]
                    }
                  }
                },
                "required": ["url", "text"]
              }
            }
          },
          "required": ["title", "items"]
        }
      },
      "userDebugInfo": {
        "type": "object",
        "properties": {
          "userDisplayName": {"type": "string"},
          "businessPartners": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {"type": "string"},
                "id": {"type": "string"}
              }
            }
          },
          "ipAddress": {"type": "string"}
        }
      },
      "image": {
        "type": "object",
        "properties": {
          "src": { "type": "string" },
          "alt": { "type": "string" },
          "link": { "type": "string" }
        },
        "required": ["src", "alt", "link"]
      },
      "currentYear": { "type": "integer" },
      "productFooter": { "type": "string" },
      "corporateFooter": { "type": "string" }
    },
    "required": ["navigation", "image", "currentYear", "productFooter", "corporateFooter"]
  }

=== sangitamane/headless-cms/src/views/partials/elements-components-templates/eds-c-footer/data/eds-c-footer.example.json
{
  "dataTest": "eds-c-footer-test",
  "dataTrackComponent": "unified-footer",
  "navigation": {
    "links": [
      {
        "text": "Your privacy choices/Manage cookies",
        "buttonProperties": "data-cc-action=\"preferences\"",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Your privacy choices/Manage cookies"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Accessibility statement",
        "url": "https://www.springernature.com/gp/info/accessibility",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Accessibility statement"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Your privacy choices/Manage cookies",
        "buttonProperties": "data-cc-action=\"preferences\"",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Your privacy choices/Manage cookies"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Accessibility statement",
        "url": "https://www.springernature.com/gp/info/accessibility",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Accessibility statement"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Your privacy choices/Manage cookies",
        "buttonProperties": "data-cc-action=\"preferences\"",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Your privacy choices/Manage cookies"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Accessibility statement",
        "url": "https://www.springernature.com/gp/info/accessibility",
        "dataAttributes": [
          {
            "name": "track-context",
            "value": "Accessibility statement"
          },
          {
            "name": "track-content-type",
            "value": "footer"
          },
          {
            "name": "track-label",
            "value": "footer"
          },
          {
            "name": "test",
            "value": "yes-test"
          }
        ]
      },
      {
        "text": "Privacy policy",
        "url": "/url/to/your/privacy/policy"
      }
    ]
  },
  "productGroups": [
    {
      "title": "Discover content",
      "items": [
        {
          "url": "https://www.nature.com/siteindex",
          "text": "Journals A-Z",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "journals a-z"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://www.nature.com/subjects/",
          "text": "Articles by subject",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "article by subject"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://nano.nature.com/",
          "text": "Nano",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "nano"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://www.nature.com/protocolexchange/",
          "text": "Protocol exchange",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "protocol exchange"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://www.natureindex.com/",
          "text": "Nature Index",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "nature index"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        }
      ]
    },
    {
      "title": "Publishing policies",
      "items": [
        {
          "url": "https://www.nature.com/authors/editorial_policies/",
          "text": "Nature portfolio policies",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "nature portfolio policies"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://www.nature.com/nature-research/open-access",
          "text": "Open access",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "open access"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        }
      ]
    },
    {
      "title": "Author & Researcher services",
      "items": [
        {
          "url": "https://www.nature.com/reprints/",
          "text": "Reprints & permissions",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "reprints and permissions"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://www.springernature.com/gp/authors/research-data",
          "text": "Research data",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "research data"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://authorservices.springernature.com/go/nr",
          "text": "Language editing",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "language editing"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
            }
          ]
        },
        {
          "url": "https://authorservices.springernature.com/scientific-editing/",
          "text": "Scientific editing",
          "dataAttributes": [
            {
              "name": "track-context",
              "value": "scientific editing"
            },
            {
              "name": "track-content-type",
              "value": "footer"
            },
            {
              "name": "track-label",
              "value": "footer"
            },
            {
              "name": "test",
              "value": "yes-test"
