=== sangitamane/headless-cms/src/views/partials/elements-components-templates/eds-c-header/data/eds-c-header.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://springernature.com/eds-c-header.schema.json",
	"title": "Header",
	"description": "Header component",
	"type": "object",
	"properties": {
		"variantDataAttribute": { "type": "string" },
		"logo": {
			"type": "object",
			"properties": {
				"link": { "type": "string" },
				"src": { "type": "string" },
				"alt": { "type": "string" },
				"dataAttributes": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string",
								"enum": [
									"test",
									"track",
									"track-context",
									"track-value",
									"track-method",
									"track-content-type",
									"track-item-id",
									"track-type",
									"track-action",
									"track-category",
									"track-label",
									"track-component"
								]
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"name",
							"value"
						]
					}
				}
			},
			"required": ["src", "alt"]
		},
		"loggedIn": { "type": "boolean" },
		"snid": { "type": "boolean" },
		"snidTemplate": { "type": "string" },
		"loginLink": {
			"type": "object",
			"properties": {
				"url": { "type": "string" },
				"text": { "type": "string" },
				"icon": { "type": "string" },
				"dataAttributes": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string",
								"enum": [
									"test",
									"track",
									"track-context",
									"track-value",
									"track-method",
									"track-content-type",
									"track-item-id",
									"track-type",
									"track-action",
									"track-category",
									"track-label",
									"track-component"
								]
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"name",
							"value"
						]
					}
				}
			},
			"required": ["url", "text"]
		},
		"accountTitle": { "type": "string" },
		"headerNavigation": {
			"type": "object",
			"properties": {
				"navigationText": { "type": "string" },
				"searchText": { "type": "string" },
				"iconSearch": { "type": "string" },
				"iconMenu": { "type": "string" },
				"links": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"url": { "type": "string" },
							"text": { "type": "string" },
							"dataAttributes": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"name": {
											"type": "string",
											"enum": [
												"test",
												"track",
												"track-context",
												"track-value",
												"track-method",
												"track-content-type",
												"track-item-id",
												"track-type",
												"track-action",
												"track-category",
												"track-label",
												"track-component"
											]
										},
										"value": {
											"type": "string"
										}
									},
									"required": [
										"name",
										"value"
									]
								}
							}
						},
						"required": ["url", "text"]
					}
				},
				"cartTemplate": { "type": "string" }
			},
			"required": [
				"navigationText",
				"searchText",
				"iconSearch",
				"iconMenu",
				"links"
			]
		},
		"headerAccount": {
			"type": "object",
			"properties": {
				"text": { "type": "string" },
				"links": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"url": { "type": "string" },
							"text": { "type": "string" },
							"dataAttributes": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"name": {
											"type": "string",
											"enum": [
												"test",
												"track",
												"track-context",
												"track-value",
												"track-method",
												"track-content-type",
												"track-item-id",
												"track-type",
												"track-action",
												"track-category",
												"track-label",
												"track-component"
											]
										},
										"value": {
											"type": "string"
										}
									},
									"required": [
										"name",
										"value"
									]
								}
							}
						},
						"required": ["url", "text"]
					}
				}
			},
			"required": ["text", "links"]
		},
		"headerSearch": {
			"type": "object",
			"properties": {
				"heading": { "type": "string" },
				"label": { "type": "string" },
				"ariaLabel": { "type": "string" },
				"url": { "type": "string" },
				"text": { "type": "string" },
				"icon": { "type": "string" },
				"dataAttributes": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string",
								"enum": [
									"test",
									"track",
									"track-context",
									"track-value",
									"track-method",
									"track-content-type",
									"track-item-id",
									"track-type",
									"track-action",
									"track-category",
									"track-label",
									"track-component"
								]
							},
							"value": {
								"type": "string"
							}
						},
						"required": [
							"name",
							"value"
						]
					}
				}
			},
			"required": ["heading", "label", "url", "text", "icon"]
		}
	},
	"required": ["logo", "loggedIn", "snid"]
}

=== sangitamane/headless-cms/src/views/partials/elements-components-templates/eds-c-header/data/eds-c-header-test.mock.json
{
    "logo": {
      "link": "/",
      "src": "/img/logo-springernature-blue.svg",
      "alt": "Logo Header"
    },
    "loggedIn": true,
    "snid": false,
    "loginLink": {
        "url": "/login",
        "dataTrackAction": "login-test",
        "text": "Login",
        "icon": "/img/eds-user-account-medium.svg#eds-i-user-account-medium"
    },
    "accountTitle": "Account",
    "headerNavigation": {
        "navigationText": "Menu",
        "searchText": "Search",
        "iconSearch": "/img/eds-search.svg#eds-i-search",
        "iconMenu": "/img/eds-menu.svg#eds-i-menu",
        "links": [
            {
                "url": "/find-a-journal-test",
                "dataTrackAction": "find-a-journal-test",
                "text": "Find a Journal"
            },
            {
              "url": "/publish-with-us-test",
              "dataTrackAction": "publish-with-us-test",
              "text": "Publish with us"
          }
        ]
    },
    "headerAccount": {
      "text": "Account",
      "links": [
        {
          "url": "/login-test",
          "dataTrackAction": "",
          "text": "Access through your institution"
        },
        {
          "url": "/login-test",
          "dataTrackAction": "",
          "text": "My account"
        },
        {
          "url": "/login-test",
          "dataTrackAction": "",
          "text": "My account bookshelf"
        },
        {
          "url": "/login-test",
          "dataTrackAction": "",
          "text": "logout"
        }
      ]
  
    },
    "headerSearch": {
      "heading": "Search",
      "label": "Search by keyword or author",
      "url": "/search-action",
      "text": "search text",
      "dataTrackAction": "search",
      "icon": "/img/eds-search.svg#eds-i-search"
    }
  }
